title: Teacher Tiago Gomes
#logo: /assets/img/minhafoto.png
description: Teacher Tiago’s Online Language Classes offers personalized Portuguese and English lessons, tailored to your goals. From private 1-on-1 sessions to structured courses, we provide a flexible and engaging way to master your language skills.
#show_downloads: true
theme: jekyll-theme-cayman
#google_analytics: [Your Google Analytics tracking ID] | But there's another way to tag in the head
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
