title: Teacher Tiago Gomes
#logo: /assets/img/minhafoto.png
description: Master Brazilian Portuguese and English Online!
#show_downloads: true
theme: jekyll-theme-cayman
#google_analytics: [Your Google Analytics tracking ID] | But there's another way to tag in the head
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
